name: Dev Prog Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  dev-train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set up Azure subscription and WS
      run: az configure --defaults group="tutorial-dev-rg" workspace="aml-tutorial-dev"

    - name: Generate job name
      run: echo "job_final_$(date +'%Y%m%d%H%M%S')" > job_name.txt

    - name: Read job name
      id: job_name
      run: echo "JOB_NAME=$(cat job_name.txt)" >> $GITHUB_ENV

    - name: Submit Azure ML job
      run: az ml job create -f src/job.yml -n ${{ env.JOB_NAME }}

  prod-train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set up Azure subscription and WS
      run: az configure --defaults group="tutorial-dev-rg" workspace="aml-tutorial-dev"

    - name: Generate job name
      run: echo "job_final_2_$(date +'%Y%m%d%H%M%S')" > job_name.txt

    - name: Read job name
      id: job_name
      run: echo "JOB_NAME=$(cat job_name.txt)" >> $GITHUB_ENV

    - name: Submit Azure ML job
      run: az ml job create -f src/job2.yml -n ${{ env.JOB_NAME }}
