name: Azure Machine Learning CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  experiment-train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login (Development)
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set up Azure subscription and WS for Development
      run: az configure --defaults group="tutorial-dev-rg" workspace="aml-tutorial-dev"

    - name: Generate job name for Development
      run: echo "job_dev_$(date +'%Y%m%d%H%M%S')" > job_name_dev.txt

    - name: Read Development job name
      id: job_name_dev
      run: echo "JOB_NAME_DEV=$(cat job_name_dev.txt)" >> $GITHUB_ENV

    - name: Submit Azure ML job for Development
      id: submit_experiment_job
      run: az ml job create -f src/job.yml -n ${{ env.JOB_NAME_DEV }}

    - name: Check Development job status
      id: check_experiment_job_status
      run: |
        status=$(az ml job show -n ${{ env.JOB_NAME_DEV }} --query 'status' -o tsv)
        echo "Job status: $status"
        echo "JOB_STATUS=$status" >> $GITHUB_ENV

  production-train:
    runs-on: ubuntu-latest
    needs: experiment-train
    if: needs.experiment-train.outputs.JOB_STATUS == 'Completed'
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login (Production)
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set up Azure subscription and WS for Production
      run: az configure --defaults group="tutorial-dev-rg" workspace="aml-tutorial-dev"

    - name: Generate job name for Production
      run: echo "job_prod_$(date +'%Y%m%d%H%M%S')" > job_name_prod.txt

    - name: Read Production job name
      id: job_name_prod
      run: echo "JOB_NAME_PROD=$(cat job_name_prod.txt)" >> $GITHUB_ENV

    - name: Submit Azure ML job for Production
      run: az ml job create -f src/job2.yml -n ${{ env.JOB_NAME_PROD }}
