name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set up Azure subscription and WS
      run: |
        az account set --subscription 1761fabd-6c59-467f-8fa7-154c65ab2a0b
        az ml workspace set -w aml-tutorial-dev -g tutorial-dev-rg
    
    - name: Submit Azure ML job
      run: az ml job create -f AML_Tutorial/src/job.yml -n "job1"



