name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
