name: Code checks

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Flake8
        run: python -m pip install flake8

      - name: Run linting tests
        run: flake8 src/model/

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
     
      - name: Pip downgrade
        run: python -m pip install --upgrade pip==23.3

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Run pytest
        run: pytest tests/test_train.py
